services:
  - type: web
    name: intlexpress-client
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    buildFilter:
      paths:
        - client/**
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: intlexpress-admin
    runtime: static
    buildCommand: cd admin-dashboard && npm install --package-lock=false && npm run build
    staticPublishPath: ./admin-dashboard/build
    buildFilter:
      paths:
        - admin-dashboard/**

  - type: web
    name: intlexpress-main-pgvy
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: PROD_BUCKET
        sync: false
      - key: R2_UPLOAD_TIMEOUT_MS
        value: 30000
    buildFilter:
      paths:
        - backend/**
