-- Synchronize the B2B additional charge table with the current advanced charge configuration.
-- Safe to run multiple times.

ALTER TABLE shiplifi_b2b_additional_charges
  ADD COLUMN IF NOT EXISTS minimum_chargeable_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS demurrage_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS green_tax numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oda_config jsonb,
  ADD COLUMN IF NOT EXISTS handling_slabs jsonb,
  ADD COLUMN IF NOT EXISTS fuel_hike_config jsonb,
  ADD COLUMN IF NOT EXISTS service_charges_config jsonb,
  ADD COLUMN IF NOT EXISTS billing_config jsonb,
  ADD COLUMN IF NOT EXISTS oda_charges numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oda_per_kg_charge numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oda_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS csd_delivery_charge numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS time_specific_per_kg numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS time_specific_per_awb numeric(12,2) DEFAULT 500,
  ADD COLUMN IF NOT EXISTS time_specific_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS mall_delivery_per_kg numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mall_delivery_per_awb numeric(12,2) DEFAULT 500,
  ADD COLUMN IF NOT EXISTS mall_delivery_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS delivery_reattempt_per_kg numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_reattempt_per_awb numeric(12,2) DEFAULT 500,
  ADD COLUMN IF NOT EXISTS delivery_reattempt_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS handling_single_piece numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS handling_below_100_kg numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS handling_100_to_200_kg numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS handling_above_200_kg numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS insurance_charge numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cod_fixed_amount numeric(12,2) DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cod_percentage numeric(6,2) DEFAULT 1,
  ADD COLUMN IF NOT EXISTS cod_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS rov_fixed_amount numeric(12,2) DEFAULT 100,
  ADD COLUMN IF NOT EXISTS rov_percentage numeric(6,2) DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS rov_method varchar(20) DEFAULT 'whichever_is_higher',
  ADD COLUMN IF NOT EXISTS liability_limit numeric(12,2) DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS liability_method varchar(20) DEFAULT 'whichever_is_lower',
  ADD COLUMN IF NOT EXISTS custom_fields jsonb,
  ADD COLUMN IF NOT EXISTS field_definitions jsonb,
  ADD COLUMN IF NOT EXISTS metadata jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now() NOT NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now() NOT NULL;
