// routes/shippingRateRoutes.ts
import { Router } from 'express'
import {
  bookDelhiveryB2BAppointmentController,
  cancelDelhiveryB2BPickupRequestController,
  createDelhiveryB2BPickupRequestController,
  cancelDelhiveryB2BShipmentController,
  checkDelhiveryB2BServiceabilityController,
  createDelhiveryB2BClientWarehouseController,
  createDelhiveryB2BShipmentController,
  getDelhiveryB2BShipmentStatusController,
  getDelhiveryB2BShipmentUpdateStatusController,
  getDelhiveryB2BLabelUrlsController,
  trackDelhiveryB2BShipmentController,
  estimateDelhiveryB2BFreightController,
  estimateDelhiveryB2BTatController,
  getDelhiveryB2BFreightChargesController,
  getCourierCredentialsController,
  deleteShippingRateController,
  fetchAvailableCouriersForAdmin,
  getAllCouriersController,
  getShippingRatesController,
  importShippingRatesController,
  loginDelhiveryB2BController,
  logoutDelhiveryB2BController,
  resetDelhiveryPasswordController,
  updateAmazonCredentialsController,
  updateDelhiveryB2BClientWarehouseController,
  updateDelhiveryB2BShipmentController,
  updateDelhiveryCredentialsController,
  updateEkartCredentialsController,
  updateShadowfaxCredentialsController,
  updateXpressbeesAwbRangeController,
  updateXpressbeesCredentialsController,
  updateShippingRateController,
} from '../../controllers/admin/courier.controller'
import { isAdminMiddleware } from '../../middlewares/isAdmin'
import { requireAuth } from '../../middlewares/requireAuth'
import { upload } from '../../middlewares/upload'

const router = Router()

router.get('/shipping-rates', getShippingRatesController)
router.get('/list', getAllCouriersController)

router.put(
  '/shipping-rate/:id/:planId',
  requireAuth,
  isAdminMiddleware,
  updateShippingRateController,
)
router.post(
  '/shipping-rates/import',
  requireAuth,
  isAdminMiddleware,
  upload.single('file'),
  importShippingRatesController,
)
router.post('/available', requireAuth, fetchAvailableCouriersForAdmin)
router.get('/credentials', requireAuth, isAdminMiddleware, getCourierCredentialsController)
router.put(
  '/credentials/delhivery',
  requireAuth,
  isAdminMiddleware,
  updateDelhiveryCredentialsController,
)
router.post(
  '/credentials/delhivery/forgot-password',
  requireAuth,
  isAdminMiddleware,
  resetDelhiveryPasswordController,
)
router.post(
  '/credentials/delhivery/login',
  requireAuth,
  isAdminMiddleware,
  loginDelhiveryB2BController,
)
router.post(
  '/credentials/delhivery/logout',
  requireAuth,
  isAdminMiddleware,
  logoutDelhiveryB2BController,
)
router.post(
  '/credentials/delhivery/serviceability',
  requireAuth,
  isAdminMiddleware,
  checkDelhiveryB2BServiceabilityController,
)
router.post(
  '/credentials/delhivery/tat',
  requireAuth,
  isAdminMiddleware,
  estimateDelhiveryB2BTatController,
)
router.post(
  '/credentials/delhivery/freight-estimate',
  requireAuth,
  isAdminMiddleware,
  estimateDelhiveryB2BFreightController,
)
router.post(
  '/credentials/delhivery/freight-charges',
  requireAuth,
  isAdminMiddleware,
  getDelhiveryB2BFreightChargesController,
)
router.post(
  '/credentials/delhivery/client-warehouse',
  requireAuth,
  isAdminMiddleware,
  createDelhiveryB2BClientWarehouseController,
)
router.patch(
  '/credentials/delhivery/client-warehouse',
  requireAuth,
  isAdminMiddleware,
  updateDelhiveryB2BClientWarehouseController,
)
router.post(
  '/credentials/delhivery/shipment',
  requireAuth,
  isAdminMiddleware,
  createDelhiveryB2BShipmentController,
)
router.post(
  '/credentials/delhivery/shipment-status',
  requireAuth,
  isAdminMiddleware,
  getDelhiveryB2BShipmentStatusController,
)
router.put(
  '/credentials/delhivery/shipment',
  requireAuth,
  isAdminMiddleware,
  updateDelhiveryB2BShipmentController,
)
router.post(
  '/credentials/delhivery/shipment-update-status',
  requireAuth,
  isAdminMiddleware,
  getDelhiveryB2BShipmentUpdateStatusController,
)
router.delete(
  '/credentials/delhivery/shipment',
  requireAuth,
  isAdminMiddleware,
  cancelDelhiveryB2BShipmentController,
)
router.post(
  '/credentials/delhivery/shipment-track',
  requireAuth,
  isAdminMiddleware,
  trackDelhiveryB2BShipmentController,
)
router.post(
  '/credentials/delhivery/appointment',
  requireAuth,
  isAdminMiddleware,
  bookDelhiveryB2BAppointmentController,
)
router.post(
  '/credentials/delhivery/pickup-request',
  requireAuth,
  isAdminMiddleware,
  createDelhiveryB2BPickupRequestController,
)
router.delete(
  '/credentials/delhivery/pickup-request',
  requireAuth,
  isAdminMiddleware,
  cancelDelhiveryB2BPickupRequestController,
)
router.post(
  '/credentials/delhivery/label-urls',
  requireAuth,
  isAdminMiddleware,
  getDelhiveryB2BLabelUrlsController,
)
router.put(
  '/credentials/ekart',
  requireAuth,
  isAdminMiddleware,
  updateEkartCredentialsController,
)
router.put(
  '/credentials/shadowfax',
  requireAuth,
  isAdminMiddleware,
  updateShadowfaxCredentialsController,
)
router.put(
  '/credentials/xpressbees',
  requireAuth,
  isAdminMiddleware,
  updateXpressbeesCredentialsController,
)
router.put(
  '/credentials/xpressbees/awb-range',
  requireAuth,
  isAdminMiddleware,
  updateXpressbeesAwbRangeController,
)
router.put(
  '/credentials/amazon',
  requireAuth,
  isAdminMiddleware,
  updateAmazonCredentialsController,
)
router.delete(
  '/shipping-rates/:planId/:id',
  requireAuth,
  isAdminMiddleware,
  deleteShippingRateController,
)

export default router
